### ISSUE TITLE
where should i can download the Dgraph.net 23.0.0?

### ISSUE THREAD

**Issue by pangjianxin** [dgraph-io/dgraph.net#36]
where should i can download the Dgraph.net 23.0.0 introduced in the README?

**Comment by benthepoet** [comment]
Same issue, trying to interface with the latest Dgraph but there's no Nuget package for published for 23.0.0.

**Comment by MichelDiz** [comment]
I don't think there is a build for 23.0.0 - You should clone the repo and build yourself.
